#!/bin/bash
# md baseline generator: render each listed content/<name>.md post with
# cora's md4c (process-file) and write the sxml->xml output to
# src-ta/test/baseline/md/<name>.md.html. Byte-identical reference for
# the ta md module (spec A2).
#
# The POSTS list is the delivered baseline set (the posts md_test.ta
# asserts against): code blocks + language class, task lists, tables,
# images, nested blockquotes, and an ordered list with start != 1.
#
# cora's evaluator is picky about nested-let/string-append script shapes
# (observed: "attempt to call a non-function object (tag=4)" on
# 2018.md), so each post gets its own flat script generated by sed from
# gen_md_baseline.cora with the path inlined — see that file's NOTE.
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/../../.."   # go.blog root

CORA_BIN="${CORA_BIN:-/Users/genius/project/cora/cora}"
OUTDIR=src-ta/test/baseline/md
mkdir -p "$OUTDIR"

POSTS=(
  200-lines-gc.md
  2018.md
  2022.md
  7900xtx-local-ai.md
  chibi-scheme1.md
  klambda.md
  raft-2F1A.md
)

for name in "${POSTS[@]}"; do
  tmp=$(mktemp /tmp/md_baseline.XXXXXX.cora)
  trap 'rm -f "$tmp"' EXIT
  sed "s|__POST__|$name|g" "$SCRIPT_DIR/gen_md_baseline.cora" > "$tmp"
  "$CORA_BIN" "$tmp" >/dev/null
  rm -f "$tmp"
  echo "  $name -> $OUTDIR/$name.html"
done
echo "md baseline done"